#test
name: Node.js CI
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  build:
    runs-on: self-hosted
    steps:
      - run: cd /var/myapps/expbot
      - run: git pull
      - run: npm i
      - run: pm2 stop expBot
      - run: pm2 start expBot
