name: Node.js CI
#agora vai pls
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  build:
    runs-on: self-hosted
    steps:
      - run: git pull
      - run: npm i
      - run: npm run dev
