#test
name: Node.js CI
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  build:
    runs-on: self-hosted
    steps:
      #- run: cd ~
      #- run: git pull https://github.com/Emanuelstori/expbot.git main
      #- run: npm i
      #- run: pm2 restart new
      #- run: npm i
      #- run: pm2 stop expBot
      #- run: pm2 start expBot
